import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/l/k/p/-original-imagqfwbfbektyhn.jpeg?q=70",
    title: "Titan NEO",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$265,",
    newPrice: "200",
    company: "Titan",
    color: "silver",
    category: "Smart-Analog",
  },

  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/p/q/n/-original-imagszc6vsjmkmbg.jpeg?q=70",
    title: "FOSSIL Analog ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$150",
    newPrice: "200",
    company: "Fossil",
    color: "black",
    category: "Smart-Analog",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/l/9/m/-original-imagrh69zhhknhyy.jpeg?q=70",
    title: "Titan Neo",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$240",
    newPrice: "150",
    company: "Titan",
    color: "black",
    category: "Smart-Analog",
  },

  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/m/y/g/-original-imagqrchrygzeav2.jpeg?q=70",
    title: "Titan rose-gold",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$245",
    newPrice: "200",
    company: "Titan",
    color: "rose-gold",
    category: "Smart-Analog",
  },

  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/j/r/s/-original-imagsyksxgtukvhh.jpeg?q=70",
    title: "CASIO Digital ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$280",
    newPrice: "200",
    company: "CASIO",
    color: "black",
    category: "Digital",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/m/p/k/-original-imagsyktkusdcczf.jpeg?q=70",
    title: "TIMEX Analog",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100",
    newPrice: "50",
    company: "TIMEX",
    color: "rose-gold",
    category: "Analog",
  },

  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/l/z/f/-original-imagsyksyb5rke6p.jpeg?q=70",
    title: "CASIO youth-digitan",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140",
    newPrice: "50",
    company: "CASIO",
    color: "blue",
    category: "Digital",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/6/g/y/-original-imagqyfhudvgj3a6.jpeg?q=70",
    title: "Titan ceramic",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140",
    newPrice: "100",
    company: "Titan",
    color: "black",
    category: "Analog",
  },

  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/s/e/z/-original-imagsykthwfcxsgw.jpeg?q=70",
    title: "TIMEX Analog  ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140",
    newPrice: "150",
    company: "Timex",
    color: "rose-gold",
    category: "Smart-Analog",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/h/u/h/-original-imagszc6sckbuhvt.jpeg?q=70",
    title: "Casio analog ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$80",
    newPrice: "50",
    company: "Casio",
    color: "black",
    category: "Analog",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/n/a/t/-original-imagszc6hgzjcxzg.jpeg?q=70",
    title: "TIMEX Rose Gold ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$150",
    newPrice: "100",
    company: "Timex",
    color: "rose-gold",
    category: "Smart-Analog",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/smartwatch/v/a/f/1-32-90137ap01-android-ios-titan-no-original-imagkzhf5mzhyeyw.jpeg?q=70",
    title: "Titan Smart ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$180",
    newPrice: "150",
    company: "Titan",
    color: "black",
    category: "Hybrid-Smart",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/2/g/u/-original-imagsyksuc6n8wsw.jpeg?q=70",
    title: "Fossil Analog",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140",
    newPrice: "100",
    company: "Fossil",
    color: "blue",
    category: "Analog",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/p/s/4/-original-imagsykvafgzfagg.jpeg?q=70",
    title: "Fossil smart",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$90",
    newPrice: "50",
    company: "Fossil",
    color: "white",
    category: "Smart-Analog",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/j/l/h/-original-imagrh69dzcjvfnh.jpeg?q=70",
    title: "Fossil Analog",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140",
    newPrice: "100",
    company: "Fossil",
    color: "silver",
    category: "Analog",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/q/t/k/1-twixw201t-timex-men-women-original-imagt99vfucq9ava.jpeg?q=70",
    title: "TIMEX Hybrid-smart ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(156 reviews)",
    prevPrice: "$140",
    newPrice: "100",
    company: "Timex",
    color: "rose-gold",
    category: "Hybrid-Smart",
  },

  {
    img: "https://rukminim2.flixcart.com/image/832/832/ju1jqfk0/watch/y/a/g/twel12704-timex-original-imaff97premv8pym.jpeg?q=70",
    title: "Timex Analog",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$110",
    newPrice: "100",
    company: "Timex",
    color: "red",
    category: "Analog",
  },

  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/r/f/q/1-twixw202t-timex-men-women-original-imagt8bhhuyvw4ge.jpeg?q=70",
    title: "TIMEX Analog ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$180",
    newPrice: "150",
    company: "Timex",
    color: "blue",
    category: "Hybrid-Smart",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/krz97rk0/watch/s/2/s/sx178-casio-original-imag5n4ma5wzhuzk.jpeg?q=70",
    title: "Casio smart watch",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$150",
    newPrice: "100",
    company: "Casio",
    color: "red",
    category: "Smart-Analog",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/x/4/l/-original-imagsykxrhfmhb8r.jpeg?q=70",
    title: "Casio Digital Watch",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140",
    newPrice: "200",
    company: "Casio",
    color: "black",
    category: "Digital",
  },

  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/q/u/r/-original-imagsykxpqaz2gth.jpeg?q=70",
    title: "Casio silver",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$75",
    newPrice: "50",
    company: "Casio",
    color: "silver",
    category: "Analog",
  },

  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/s/h/h/-original-imagta7u28vuuycf.jpeg?q=70",
    title: "Casio Sheen",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$135",
    newPrice: "100",
    company: "Casio",
    color: "blue",
    category: "Analog",
  },

  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/2/m/y/-original-imagswy67hbcnsnb.jpeg?q=70",
    title: "Timex White",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$240",
    newPrice: "200",
    company: "Timex",
    color: "white",
    category: "Analog",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/2/o/o/1-95247wl01-titan-women-original-imagrufcthtahcvg.jpeg?q=70",
    title: "Titan Leather",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$170",
    newPrice: "150",
    company: "Titan",
    color: "red",
    category: "Analog",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/jbgtnrk0/watch/v/w/3/2525nl02-titan-original-imafythr8nctzgae.jpeg?q=70",
    title: "Titan Ceramic",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$170",
    newPrice: "150",
    company: "Titan",
    color: "red",
    category: "Smart-Analog",
  },

  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/b/u/g/-original-imagsykvcgc8nfza.jpeg?q=70",
    title: "Fossil Rose gold",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$120",
    newPrice: "100",
    company: "Fossil",
    color: "rose-gold",
    category: "Analog",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/6/w/w/-original-imagqfwbyhcjdam5.jpeg?q=70",
    title: "Titan smart",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$170",
    newPrice: "150",
    company: "Titan",
    color: "silver",
    category: "Smart-Analog",
  },

  {
    img: "https://rukminim2.flixcart.com/image/832/832/k0mqtu80/smartwatch/j/c/u/ftw6035-fossil-original-imafkduxkw29fh78.jpeg?q=70",
    title: "Fossil Digital Watch",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140",
    newPrice: "200",
    company: "Fossil",
    color: "rose-gold",
    category: "Hybrid-Smart",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/k1b1bbk0/smartwatch/v/5/z/iconnect-2-timex-original-imafkycvuh8394mz.jpeg?q=70",
    title: "TIMEX Digital Watch",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140",
    newPrice: "200",
    company: "TIMEX",
    color: "black",
    category: "Hybrid-Smart",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/jyoq93k0/smartwatch/g/u/8/ftw4019-fossil-original-imafgvg9uaurzx3a.jpeg?q=70",
    title: "Fossil Digital Watch",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140",
    newPrice: "200",
    company: "Fossil",
    color: "black",
    category: "Hybrid-Smart",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/k1b1bbk0/smartwatch/v/5/z/iconnect-2-timex-original-imafkycvuh8394mz.jpeg?q=70",
    title: "TIMEX Digital Watch",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$90",
    newPrice: "50",
    company: "TIMEX",
    color: "black",
    category: "Hybrid-Smart",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/j2dltow0/watch/z/y/3/es3020-fossil-original-imaetq3fgudn2ub4.jpeg?q=70",
    title: "Fossil Analog",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140",
    newPrice: "150",
    company: "Fossil",
    color: "rose-gold",
    category: "Analog",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/8/z/j/1-twixw204t-timex-men-women-original-imagt8bqmz2rkuzg.jpeg?q=70",
    title: "TIMEX Hybrid Smartwatch ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140",
    newPrice: "150",
    company: "Timex",
    color: "white",
    category: "Hybrid-Smart",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/m/f/z/-original-imagqrchyezurhpg.jpeg?q=70",
    title: "Titan ceramic ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100",
    newPrice: "50",
    company: "Titan",
    color: "white",
    category: "Analog",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/krz97rk0/watch/m/a/5/sx226-casio-original-imag5n4mtwtf7cdt.jpeg?q=70",
    title: "Casio Sheen ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100",
    newPrice: "50",
    company: "Casio",
    color: "white",
    category: "Smart-Analog",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/jpbic280/smartwatch/n/k/q/ftw4011-fossil-original-imafbh8yruua3zhg.jpeg?q=70",
    title: "Fossil Hybrid Smartwatch ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140",
    newPrice: "150",
    company: "Fossil",
    color: "silver",
    category: "Hybrid-Smart",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/a/r/n/-original-imaghgq4mgwyum6s.jpeg?q=70",
    title: "Casio digital",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$240",
    newPrice: "200",
    company: "Casio",
    color: "red",
    category: "Digital",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/g/m/v/-original-imagsykqwpezfvew.jpeg?q=70",
    title: "Titan Analog",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$190",
    newPrice: "150",
    company: "Titan",
    color: "rose-gold",
    category: "Analog",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/a/j/k/-original-imagswy5chyphere.jpeg?q=70",
    title: "Casio Enticer",
    star: <AiFillStar className="rating-star" />,
    reviews: "(100 reviews)",
    prevPrice: "$190",
    newPrice: "150",
    company: "Casio",
    color: "rose-gold",
    category: "Analog",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/u/m/m/-original-imagrh6ahdmswkyw.jpeg?q=70",
    title: "Casio Sheen",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$210",
    newPrice: "200",
    company: "Casio",
    color: "blue",
    category: "Smart-Analog",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/l/1/h/-original-imagsykxe5hh666t.jpeg?q=70",
    title: "Timex Analog",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$190",
    newPrice: "150",
    company: "Timex",
    color: "blue",
    category: "Analog",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/2/m/v/-original-imagsykvcfyqeyus.jpeg?q=70",
    title: "Fossil Analog",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$90",
    newPrice: "50",
    company: "Fossil",
    color: "silver",
    category: "Smart-Analog",
  },

  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/b/q/z/-original-imagsykvjhegfgxn.jpeg?q=70",
    title: "Timex Analog",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$190",
    newPrice: "50",
    company: "Timex",
    color: "black",
    category: "Analog",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/n/k/m/-original-imagt7fku7sxuvew.jpeg?q=70",
    title: "Timex Analog",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$180",
    newPrice: "150",
    company: "Timex",
    color: "silver",
    category: "Smart-Analog",
  },

  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/y/8/i/-original-imagsrjpnjfmcfjj.jpeg?q=70",
    title: "Timex Analog",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$290",
    newPrice: "200",
    company: "Timex",
    color: "rose-gold",
    category: "Analog",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/0/n/z/-original-imagptvydqzh3gge.jpeg?q=70",
    title: "Titan Edge",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100",
    newPrice: "50",
    company: "Titan",
    color: "black",
    category: "Analog",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/kosxzm80/watch/k/5/v/twtl87smu05-timex-original-imag36ewhbhhabjr.jpeg?q=70",
    title: "Timex Analog",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$190",
    newPrice: "100",
    company: "Timex",
    color: "red",
    category: "Analog",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/m/n/s/-original-imagswy6xzj7ckzr.jpeg?q=70",
    title: "Casio Enticer",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$170",
    newPrice: "150",
    company: "Casio",
    color: "rose-gold",
    category: "Analog",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/s/l/3/-original-imags4b9m2uhvqbc.jpeg?q=70",
    title: "Casio Analog",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$160",
    newPrice: "150",
    company: "Casio",
    color: "rose-gold",
    category: "Analog",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/f/p/v/-original-imagrh6bu5zf5cws.jpeg?q=70",
    title: "Titan ceramic white",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$190",
    newPrice: "100",
    company: "Titan",
    color: "white",
    category: "Analog",
  },
];

export default data;
